### ISSUE TITLE
why you use avg_pool instead of max_pool in the vgg model?

### ISSUE THREAD

**Issue by Edwardmark** [shekkizh/FCN.tensorflow#26]
In FCN.py, line 61, why you use avg_pool?

**Comment by ding-s-h** [comment]
I have the same question. I think in the paper the authors used max pooling. Is there any reason such choice is made in this implementation? Also, if I understand correctly, the network after VGG is slightly different from that describes in the paper?

**Comment by obendidi** [comment]
did you try using the max_pool instead of avg_pool to see if there is any change on the predictions ?

**Comment by shekkizh** [comment]
The choice of avg_pool / max_pool shouldn't affect the model prediction much in my opinion. 
With avg_pool a network makes prediction that has consensus with multiple activations while max pool makes a prediction based on strongest activation. This was my thought process while implementing FCN. 
@DingGit I believe the original paper has undergone revisions since it was published first. Can you let know how the implementation varies from the paper?
