### ISSUE TITLE
FCN vs Deepmask

### ISSUE THREAD

**Issue by pbrazdil** [shekkizh/FCN.tensorflow#3]
Hi, you have more experience in ML and computer vision so I just want to know your opinion on Image Segmentation.

What do you think will yield better results in a case of image segmentation, this implementation of FCN or Deepmask from Facebook? Can you also elaborate on why?

Right know I am in the phase of learning, so thank you for any insight.

**Comment by shekkizh** [comment]
Hi,
Thanks for your question. FCNs differ from Deepmask and earlier segmentation models in that they are very simple to implement and work with. Having said that FCNs do suffer from defining clear annotations because they are trained without explicit definition of an object, an idea that has been exploited in later papers.
If you are just looking to pick a code and use it for segmentation, between the two I would suggest Deepmask/ Sharpmask as I do believe it's results would be much cleaner. But if you plan to do research on segmentation FCNs will be the way to go.

Cheers.
