### ISSUE TITLE
How can I train arbitrary sized images?

### ISSUE THREAD

**Issue by tianjihx** [shekkizh/FCN.tensorflow#39]
Hello, thanks for your code firstly.

I found this problem was previously discussed as issue #18, I am very sad...I try to change the code at "image_options = {'resize': False}" and change the image and annotation's placeholder  "IMAGE_SIZE" to "None", but it always throws the "ValueError: setting an array element with a sequence." So it still can't be solved now ? 

But I really want to get an predict image,  whose size is as same as the original input image (un-resized). How can I solve this problem?

Thanks in advance!

**Comment by Yc174** [comment]
@tianjihx Have you solved this problem? I occured the same error.Can you help me?

**Comment by shekkizh** [comment]
Hi,
I'm not able to understand the issue posted here. If you are talking about training and predicting with variable image size, the problem is that tensorflow has static graph after initialization and hence needs to know the size of input when building the graph.
You pretty much have to do a few work arounds to predict variable size images.
